name: Format
on:
  workflow_call:
  workflow_dispatch: # to trigger manually

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "latest"

      - name: Install dependencies
        run: |
          echo "ğŸ“¦ Installing all dependencies..."
          npm install -g markdownlint-cli
          sudo apt-get update
          sudo apt-get install -y shellcheck yamllint
          sudo snap install shfmt

      - name: Run markdownlint
        run: |
          echo "ğŸ“ Running markdownlint..."
          markdownlint -- **/*.md

      - name: Run ShellCheck
        run: |
          echo "ğŸš Running ShellCheck..."
          shellcheck -- **/*.sh || exit 1

      - name: Run shfmt
        run: |
          echo "âœ¨ Checking formatting using shfmt..."
          shfmt -d -- **/*.sh

      - name: Run yamllint
        run: |
          echo "ğŸ” Running yamllint..."
          yamllint -f colored .